# Generated by Django 6.0.4 on 2026-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
