# Generated by Django 6.0.4 on 2026-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadoworderlog',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
