# Generated by Django 6.0.4 on 2026-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_image_url_alter_heroslide_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
