# Generated by Django 6.0.4 on 2026-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_base_discount_price_product_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Browser Visitor',
                'verbose_name_plural': 'Browser Visitors',
            },
        ),
    ]
