# Generated by Django 6.0.4 on 2026-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_browser_visitor_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='browservisitor',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
